version: 0.5.2.{build}
os: Windows Server 2012 R2
environment:

  matrix:
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    # TODO: Miniconda
install:
- "%PYTHON%\\Scripts\\pip install -r requirements-tests.txt"
build: off
test_script:
- "%PYTHON%\\Scripts\\py.test"
