version: 0.9.19.{build}
os: Windows Server 2012 R2
environment:

  matrix:
    # http://www.appveyor.com/docs/installed-software#python
    - XONSH_TEST_ENV: "MSYS2"
      MSYS2_PATH: "C:\\msys64"

matrix:
  allow_failures:
    # ignore MSYS2 test results for now
    - XONSH_TEST_ENV: "MSYS2"

install:
  - ".appveyor_install.cmd"
build: off
test_script:
  - ".appveyor_test.cmd"
