version: 0.1.6.{build}
os: Windows Server 2012 R2
install:
- C:\Python34\Scripts\pip install ply pyreadline nose prompt_toolkit
#- C:\Python35\Scripts\pip install ply pyreadline nose prompt_toolkit
build_script:
- C:\Python34\python setup.py install
#- C:\Python35\python setup.py install
test_script:
- C:\Python34\Scripts\nosetests
#- C:\Python35\Scripts\nosetests

