version: 0.8.0.{build}
os: Windows Server 2012 R2
environment:

  matrix:
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - XONSH_TEST_ENV: "MSYS2"
      MSYS2_PATH: "C:\\msys64"
    # TODO: Miniconda

matrix:
  allow_failures:
    # ignore MSYS2 test results for now
    - XONSH_TEST_ENV: "MSYS2"

install:
  - ".appveyor_install.cmd"
build: off
test_script:
  - ".appveyor_test.cmd"
