name: 3.8-xonsh-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pygments
  - prompt_toolkit
  - pytest
  - pytest-timeout
  - numpy
  - psutil
  - matplotlib
  - flake8
  - mypy=0.782
  - coverage
  - pyflakes
  - pytest-cov
  - codecov
