name: 3.5-xonsh-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - pygments
  - prompt_toolkit
  - pytest
  - pytest-timeout
  - numpy
  - psutil
  - flake8
  - coverage
  - pyflakes
  - pytest-cov
  - pytest-flake8
  - codecov
