name: 3.6-xonsh-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pygments
  - prompt_toolkit
  - pytest
  - pytest-timeout
  - numpy
  - psutil
  - matplotlib
  - flake8
  - mypy
  - coverage
  - pyflakes
  - pytest-cov
  - codecov
