name: Check Elm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python 3.7 Elm Check Ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: elm-xonsh-test
          environment-file: ci/environment-elm.yml
          update-conda: true
          python-version: 3.7
          condarc-file: ci/condarc.yml
      - shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          pushd xonsh/webconfig
          python -m xonsh elm-compile.xsh
          popd
